build-all:
	g++ -g -o bin/e1 src/e1.cpp
	g++ -g -o bin/e2 src/e2.cpp src/e2_parser.cpp -lm -std=c++11

build-e1:
	g++ -g -o bin/e1 src/e1.cpp

build-e2:
	g++ -g -o bin/e2 src/e2.cpp src/e2_parser.cpp -lm -std=c++11

